---
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---
# SR18 mismatches

```{r}
source("R/get_FCT.R")
d <- read.csv("data/FCTTitles.csv")
d  <- d[,c("Code_FAOFBS", "Item_FAOFBS", "PHYTAC", "PCT2_FAO", "Code_FAOPIE", "Item_FAOPIE", "PCT1", "NDB_No", "Shrt_Desc")]
names(d)  <- c("Code_FdGp1", "Item_FdGp1", "PHYTAC", "PCT1_2", "Code_FdGp2", "Item_FdGp2", "PCT2_3", "Code_FdGp3", "Item_FdGp3")
FCTP <- .getUSDA()
FCTS <- .FCT_Sup_data()
FCTP  <- FCTP[,c("NDB_No", "Long_Desc", "Tagname", "NutrDesc", "Units", "Nutr_Val")]
names(FCTP) <- c("Code_FdGp3", "Item_FdGp3", "Tagname", "MNutrDesc", "Units_MNutr", "MNutr_Val")
FCTS  <- FCTS[,c("WA_NDB_No", "WA_Shrt_Desc", "Tagname", "NutrDesc", "Units", "Nutr_Val")]
names(FCTS) <-c("Code_FdGp3", "Item_FdGp3", "Tagname", "MNutrDesc", "Units_MNutr", "MNutr_Val")
FCT_data  <- rbind(FCTP, FCTS)
FCT  <- merge(d, FCT_data, all.x = TRUE, by=c("Code_FdGp3", "Item_FdGp3"))
FCT  <- FCT[,c("Code_FdGp1", "Item_FdGp1", "PHYTAC", "PCT1_2", "Code_FdGp2", "Item_FdGp2", "PCT2_3", "Code_FdGp3", "Item_FdGp3", "Tagname", "MNutrDesc", "Units_MNutr", "MNutr_Val")]
FCT <- FCT[!is.na(FCT$PCT2_3 ), ]	
i <- is.na(FCT$MNutrDesc) & is.na(FCT$Tagname)
bad <- FCT[i, ]
u = unique(bad[,c(8:9)])
nomatch <- sort(u[,2])
```

Food group items that no long match SR
```{r}
nomatch
```


```{r}
# food group items in SR18
ufg <- unique(FCTP$Item_FdGp3)
newmatch = rep("", length(nomatch))
print(nomatch[1])
print(grep("Babyfood, cereal", ufg, value=TRUE))
newmatch[1] = "Babyfood, cereal, mixed, dry fortified"
cat("\n-----\n")

print(nomatch[2:5])
print(grep("Beef, New Zealand", ufg, value=TRUE))
newmatch[2] = "Beef, New Zealand, imported, variety meats and by-products, kidney, cooked, boiled"
newmatch[3] = "Beef, New Zealand, imported, variety meats and by-products liver, cooked, boiled"
newmatch[4] = "Beef, New Zealand, imported, variety meats and by-products tongue, cooked, boiled"
newmatch[5] = "Beef, New Zealand, imported, variety meats and by-products, tripe uncooked, raw"
cat("\n-----\n")




print(nomatch[c(6,18,27:28)])
print(grep("\\btea\\b", ufg, ignore.case=TRUE, value=TRUE))
newmatch[6] = "Beverages, tea, green, brewed, regular"
newmatch[18] = "Beverages, tea, hibiscus, brewed"
newmatch[27] = "Beverages, tea, black, brewed, prepared with tap water"
newmatch[28] = "Beverages, tea, herb, other than chamomile, brewed"


cat("\n-----\n")


print(nomatch[7])
print(grep("cocoa", ufg, ignore.case=TRUE, value=TRUE))
newmatch[7] = "Cocoa mix, NESTLE, Rich Chocolate Hot Cocoa Mix"
cat("\n-----\n")

  
print(nomatch[8:9])
print(grep("Beverages, coffee", ufg, value=TRUE))
newmatch[8] = "Beverages, coffee, brewed, prepared with tap water"
newmatch[9] = "Beverages, coffee, instant, regular, powder"
cat("\n-----\n")


print(nomatch[10:11])
print(grep("Crustaceans, shrimp", ufg, value=TRUE))
newmatch[10] = "Crustaceans, shrimp, mixed species, cooked, moist heat (may have been previously frozen)"
newmatch[11] = "Crustaceans, shrimp, cooked (not previously frozen)"
cat("\n-----\n")

print(nomatch[12:13])
print(grep("Fish, cod", ufg, value=TRUE))
newmatch[12] = "Fish, cod, Pacific, cooked, dry heat (may have been previously frozen)"
newmatch[13] = "Fish, cod, Pacific, cooked (not previously frozen)"
cat("\n-----\n")

# no longer included?
print(nomatch[14])
print(grep("dolphin", ufg, ignore.case=TRUE, value=TRUE))
cat("\n-----\n")

print(nomatch[15:16])
print(grep("Fish, pollock", ufg, value=TRUE))
newmatch[15] = "Fish, pollock, Alaska, cooked, dry heat (may have been previously frozen)"
newmatch[16] = "Fish, pollock, Alaska, cooked (not previously frozen)"
cat("\n-----\n")


print(nomatch[17])
print(grep("Fish, salmon, sockey", ufg, value=TRUE))
newmatch[17] = "Fish, salmon, sockeye, cooked, dry heat"
cat("\n-----\n")


print(nomatch[19])
print(grep("Kiwifruit", ufg, ignore.case=TRUE, value=TRUE))
newmatch[19] = "Kiwifruit, ZESPRI SunGold, raw"
cat("\n-----\n")

print(nomatch[20])
print(grep("Pasta, cooked", ufg, ignore.case=TRUE, value=TRUE))
newmatch[20] = "Pasta, cooked, unenriched, with added salt"
cat("\n-----\n")


print(nomatch[21])
print(grep("Pork Sausage", ufg, ignore.case=TRUE, value=TRUE))
newmatch[21] = "Pork sausage, link/patty, cooked, pan-fried"
cat("\n-----\n")


# Does this exist? corn-pasta?
print(nomatch[22])
print(grep("Pasta", ufg, ignore.case=TRUE, value=TRUE))
cat("\n-----\n")


print(nomatch[23])
print(grep("Peaches", ufg, ignore.case=TRUE, value=TRUE))
newmatch[23] = "Peaches, yellow, raw"
cat("\n-----\n")


print(nomatch[24])
print(grep("Rice, white, glut", ufg, ignore.case=TRUE, value=TRUE))
newmatch[24] = "Rice, white, glutinous, unenriched, cooked"
cat("\n-----\n")

print(nomatch[25])
print(grep("Rice, white, long-grain, regular", ufg, ignore.case=TRUE, value=TRUE))
newmatch[25] = "Rice, white, long-grain, regular, unenriched, cooked without salt"
cat("\n-----\n")

print(nomatch[26])
print(grep("Spices, mustard", ufg, ignore.case=TRUE, value=TRUE))
newmatch[26] = "Spices, mustard seed, ground"
```


Preliminary result 

```{r}
r = cbind(old=nomatch, new=newmatch)
for (i in 1:nrow(r)) {
  print(r[i,1])
  print(r[i,2]) 
  print("---")
}


```